export enum Permission {
  // USER
  USER_CREATE = 'UC',
  USER_READ = 'UR',
  USER_UPDATE = 'UU',
  USER_DELETE = 'UD',

  // PHONE
  PHONE_CREATE = 'PC',
  PHONE_READ = 'PR',
  PHONE_UPDATE = 'PU',
  PHONE_DELETE = 'PD',

  // DRIVER
  DRIVER_CREATE = 'DC',
  DRIVER_READ = 'DR',
  DRIVER_UPDATE = 'DU',
  DRIVER_DELETE = 'DD',

  // EMPLOYMENT
  EMPLOYMENT_CREATE = 'EC',
  EMPLOYMENT_READ = 'ER',
  EMPLOYMENT_UPDATE = 'EU',
  EMPLOYMENT_DELETE = 'ED',

  // DOCUMENT
  DOCUMENT_CREATE = 'DOCC',
  DOCUMENT_READ = 'DOCR',
  DOCUMENT_UPDATE = 'DOCU',
  DOCUMENT_DELETE = 'DOCD',

  // DOCUMENT TYPE
  DOCUMENT_TYPE_CREATE = 'DOCTC',
  DOCUMENT_TYPE_READ = 'DOCTR',
  DOCUMENT_TYPE_UPDATE = 'DOCTU',
  DOCUMENT_TYPE_DELETE = 'DOCTD',

  // INSPECTION DETAIL
  INSPECTION_DETAIL_CREATE = 'IDC',
  INSPECTION_DETAIL_READ = 'IDR',
  INSPECTION_DETAIL_UPDATE = 'IDU',
  INSPECTION_DETAIL_DELETE = 'IDD',

  // TAILING RECORD
  TAILING_RECORD_CREATE = 'TRC',
  TAILING_RECORD_READ = 'TRR',
  TAILING_RECORD_UPDATE = 'TRU',
  TAILING_RECORD_DELETE = 'TRD',

  // TAILING GRADE
  TAILING_GRADE_CREATE = 'TGC',
  TAILING_GRADE_READ = 'TGR',
  TAILING_GRADE_UPDATE = 'TGU',
  TAILING_GRADE_DELETE = 'TGD',
}
